<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<OutputPath>..\..\output\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="PrefDataManager">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>bb65111f-611b-4891-8a37-200ccdd0a115</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="PrefSales">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>c1694be9-8281-4ae9-805c-f536fbc09377</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.9" />
    <PackageReference Include="Serilog.Extensions" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\a2p.Application\a2p.Application.csproj" />
    <ProjectReference Include="..\a2p.Domain\a2p.Domain.csproj" />
  </ItemGroup>

</Project>
