<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net9.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	  <OutputPath>..\..\output\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
	<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\a2p.Application\Application.csproj" />
    <ProjectReference Include="..\a2p.Domain\Domain.csproj" />
    <ProjectReference Include="..\a2p.Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
