name: Build A2P and Create MSI Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # GitHub-hosted Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore a2p.sln

    - name: Generate Version Number
      id: version
      run: echo "VERSION=1.0.${{ github.run_number }}.0" >> $GITHUB_ENV

    - name: Update Assembly Version
      run: |
        $version = "${{ env.VERSION }}"
        (Get-ChildItem -Path src -Recurse -Include AssemblyInfo.cs) | ForEach-Object {
          (Get-Content $_.FullName) -replace 'AssemblyVersion\(".*?"\)', "AssemblyVersion(`"$version`")" |
          Set-Content $_.FullName
        }

    - name: Update WiX Installer Version
      run: |
        $version = "${{ env.VERSION }}"
        (Get-Content src/a2p.installer.wixproj) -replace '<Version>.*?</Version>', "<Version>$version</Version>" |
        Set-Content src/a2p.installer.wixproj

    - name: Build Solution
      run: dotnet build a2p.sln --configuration Release --no-restore

    - name: Install WiX Toolset 5
      run: dotnet tool install --global wix --version 5.0.2

    - name: Build WiX Installer
      run: dotnet build src/a2p.installer.wixproj --configuration Release --no-restore

    - name: Upload MSI as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: A2P-Installer
        path: Output/*.msi
